### ISSUE TITLE
Zmienić sposób ładowania klas filtrów.

### ISSUE THREAD

**Issue by krystofair** [krystofair/system-filtracji-cyfrowej#5]
Aktualnie, aby dodać nowy filtr należy dodać plik z jego implementacją do katalogu "filters" i ręcznie w pliku "__init__" tego modułu dodać odpowiedni kod. Nowa zmiana powinna robić to automatycznie, wymagając od użytkownika jedynie dodania pliku z implementacją filtru, którego klasa dziedziczy po interfejsie.

**Comment by mhanzel** [comment]
Potwierdzam
